package com.paranoiax.core_infra.rest.exceptions;

public enum ApiErrorCode {
    FIELD_REQUIRED,
    INVALID_DEVICE_TYPE,
    INTERNAL_SERVER_ERROR,
    MESSAGE_NOT_READABLE,
    MISSING_REQUEST_HEADER,
    MISSING_REQUEST_PARAM,
    METHOD_NOT_ALLOWED,
    UNSUPPORTED_MEDIA_TYPE,
    METHOD_ARGUMENT_TYPE_MISMATCH,
    UNAUTHORIZED,
    ACCESS_DENIED,
    NOT_FOUND,
    NOT_SUPPORTED_YET,
    NUMBER_MUST_BE_POSITIVE,
    TIMESTAMP_MUST_BE_IN_FUTURE
}