server:
  port: 8081

management:
  endpoint:
    info:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  prometheus:
    metrics:
      export:
        enabled: true

  otlp:
    metrics:
      export:
        enabled: false

spring:
  application:
    name: users

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: users

  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5433}/${DB_DATABASE:paranoiax}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  data:
    redis:
      host: ${REDIS_HOSTNAME:localhost}
      port: ${REDIS_PORT:6379}

  jackson:
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

application:
  public-host: ${APP_PUBLIC_HOST:8080}
  spki-pin: ${APP_SPKI_PIN:sha256/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=}
  invite:
    lock-ttl: 5
    token-ttl: 900
