server:
  port: 8081
  forward-headers-strategy: framework

management:
  endpoint:
    info:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  prometheus:
    metrics:
      export:
        enabled: true

  otlp:
    metrics:
      export:
        enabled: false

spring:
  application:
    name: users

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 105MB

  liquibase:
    default-schema: users

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: users

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:users}
      auto-offset-reset: earliest

  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5433}/${DB_DATABASE:paranoiax}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  data:
    redis:
      host: ${REDIS_HOSTNAME:localhost}
      port: ${REDIS_PORT:6379}

  jackson:
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

application:
  public-host: ${APP_PUBLIC_HOST:localhost:8080}
  spki-pin: ${APP_SPKI_PIN:sha256/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=}
  auth:
    invite:
      lock-ttl: 5s
      result-ttl: 15m
      token-size: 32
    register:
      invite-only: ${APP_REGISTER_INVITE_ONLY:true}
      lock-ttl: 30s
      result-ttl: 1d
    challenge:
      lock-ttl: 5s
      result-ttl: 1m
      token-size: 32
    challenge-auth:
      lock-ttl: 5s
      result-ttl: 1m
    refresh:
      lock-ttl: 5s
      result-ttl: 1m
  devices:
    migrations:
      complete-upload:
        lock-ttl: 5s
        result-ttl: 1m
        token-size: 32
      generate-download-url:
        lock-ttl: 5s
        result-ttl: 1m
    register:
      lock-ttl: 30s
      result-ttl: 1d
  profile:
    get-user-ids:
      max-batch-size: 256

jwt:
  keys:
    private: ${JWT_PRIVATE_KEY}
    public: ${JWT_PUBLIC_KEY}
  acccess:
    ttl: 15m
  refresh:
    ttl: 30d

s3:
  endpoint: ${S3_ENDPOINT:http://localhost:8333}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  lock-ttl: 10s
  result-ttl: 15m
  migration:
    bucket: migrations