package com.paranoiax.users.infrastructure.rest.exceptions;

public enum ApiErrorCode {
    FIELD_REQUIRED,
    INVALID_DEVICE_TYPE,
    INTERNAL_SERVER_ERROR,
    MESSAGE_NOT_READABLE,
    MISSING_REQUEST_HEADER,
    METHOD_NOT_ALLOWED,
    UNSUPPORTED_MEDIA_TYPE,
    METHOD_ARGUMENT_TYPE_MISMATCH,
    UNAUTHORIZED,
    ACCESS_DENIED,
    NOT_FOUND
}